name: Keycloak Regression Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Append client credential to properties file  
      run: echo "admin_client_secret=${{ secrets.ADMIN_CLIENT_SECRET }}" >> env/${{env.ENV}}.properties
    
    - name: Append prm credential to properties file
      run: echo "prm_token=${{ secrets.PRM_TOKEN }}" >> env/${{env.ENV}}.properties

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with Maven
      run: mvn clean test -P${{env.ENV}}
