name: Keycloak Regression Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  Regression:

    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}

    steps:

      - uses: actions/checkout@v3
      - name: Echo client credential engg
        run: echo "admin_client_secret=${{ secrets.ADMIN_CLIENT_SECRET }}" >> ./env/${{vars.ENV}}.properties
        if: inputs.environment == 'Engg'
  
      - name: Echo client creds stage
        run: echo "STAGE=${{ secrets.ADMIN_CLIENT_SECRET }}"
        if: inputs.environment == 'Stage'
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests with Maven
        run: mvn clean test -P${{vars.ENV}}
