name: Keycloak Regression Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Echo client credential
      run: echo "admin_client_secret=${{ secrets.ADMIN_CLIENT_SECRET }}"
